import WealthManagement.*;
import java.util.*;

/**
 *
 * @author Franco
 */
public class WealthManagerForm extends javax.swing.JFrame {
    
    private Vector<Asset> assets = new Vector<>();

    /**
     * Creates new form WealthManagerForm
     */
    public WealthManagerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAssets = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListAssets = new javax.swing.JList<>();
        LabelAssetDetail = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaAssetDetail = new javax.swing.JTextArea();
        PanelVisualSummary = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        MenuButtonNew = new javax.swing.JMenu();
        MenuItemBankAccount = new javax.swing.JMenuItem();
        MenuItemStock = new javax.swing.JMenuItem();
        MenuItemHouse = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wealth Manager");

        LabelAssets.setText("Assets");

        jScrollPane1.setViewportView(ListAssets);

        LabelAssetDetail.setText("Asset Detail");

        TextAreaAssetDetail.setColumns(20);
        TextAreaAssetDetail.setRows(5);
        jScrollPane2.setViewportView(TextAreaAssetDetail);

        jLabel1.setText("Net Worth: ");

        javax.swing.GroupLayout PanelVisualSummaryLayout = new javax.swing.GroupLayout(PanelVisualSummary);
        PanelVisualSummary.setLayout(PanelVisualSummaryLayout);
        PanelVisualSummaryLayout.setHorizontalGroup(
            PanelVisualSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVisualSummaryLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelVisualSummaryLayout.setVerticalGroup(
            PanelVisualSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVisualSummaryLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        MenuButtonNew.setText("New");

        MenuItemBankAccount.setText("Bank Account");
        MenuItemBankAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemBankAccountActionPerformed(evt);
            }
        });
        MenuButtonNew.add(MenuItemBankAccount);

        MenuItemStock.setText("Stock");
        MenuItemStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStockActionPerformed(evt);
            }
        });
        MenuButtonNew.add(MenuItemStock);

        MenuItemHouse.setText("Property");
        MenuItemHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemHouseActionPerformed(evt);
            }
        });
        MenuButtonNew.add(MenuItemHouse);

        MenuBar.add(MenuButtonNew);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelAssets)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAssetDetail)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(PanelVisualSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAssets)
                    .addComponent(LabelAssetDetail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelVisualSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemBankAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemBankAccountActionPerformed
        BankAccountForm baf = new BankAccountForm();
        baf.setVisible(true);
    }//GEN-LAST:event_MenuItemBankAccountActionPerformed

    private void MenuItemStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStockActionPerformed
        StockForm sf = new StockForm();
        sf.setVisible(true);
    }//GEN-LAST:event_MenuItemStockActionPerformed

    private void MenuItemHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemHouseActionPerformed
        PropertyForm hf = new PropertyForm();
        hf.setVisible(true);
    }//GEN-LAST:event_MenuItemHouseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WealthManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WealthManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WealthManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WealthManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WealthManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAssetDetail;
    private javax.swing.JLabel LabelAssets;
    private javax.swing.JList<String> ListAssets;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuButtonNew;
    private javax.swing.JMenuItem MenuItemBankAccount;
    private javax.swing.JMenuItem MenuItemHouse;
    private javax.swing.JMenuItem MenuItemStock;
    private javax.swing.JPanel PanelVisualSummary;
    private javax.swing.JTextArea TextAreaAssetDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
